{% set version = "0.4.1" %}

package:
  name: sat-stac
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sat-stac/sat-stac-{{ version }}.tar.gz
  sha256: a06bb3491ee49497262d228e9c8aed4d68d89e7dff140e2439f199dd92864f2c

build:
  number: 3
  noarch: python
  entry_points:
    - sat-stac=satstac.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.7.5
    - requests >=2.19.1

test:
  imports:
    - satstac
  commands:
    - pip check
    - sat-stac --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sat-utils/sat-stac.git
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for working with Spatio-Temporal Asset Catalogs (STAC)

extra:
  recipe-maintainers:
    - ocefpaf
