travis:
  secure:
    BINSTAR_TOKEN: Q3mC5JZnN504qeeMpwxHh7xL4lkyZrhoN5VD3kNORMB0BufykWvLXE50OjwdJq5//+kKVvsfqA2uwqy3MBU4wNInu+60pO0VGuy8kyZ87dAyL5gCKAvtKDPB3Glb3/xrfZBmqexCPrPuPpJoK8BcNG0FbDFvEzCUVF9zbwLuMVt9NPGTUZiS2gfz8215iPprYYMbscrL5sJEMXOM7fUZoqzIlFEAxRrznPAWeX7jIF9h2l9wO3Un6wS+ArlrRHz+KdcfQy5a2mansOHC2oiWB+LqUASnNXAuF2EjJTBNVIISKWWWfofWWFDmgP0pRLYUKsEbgccmhJkvy7yAdwbvUYvVhIa5EiMb44TbhcP6M5ULmuzbx7GyNeUf8i0/s0tsLEjYbZye1B6LvPPspNGVrfIAd2d2f5CyNqKA7t/JjRBUZaMmd/X5xktVD3WozNTv+XhyL+8qmERuKn79Vk5gO0U5vFBGZIbWaUClbSrUDfHDLUGuxKINFHRLRc3ek1V33j73FqsoZR7hmDuNRVrvWmcFS4IEHO5BeoFyJLwzWrj7SBphlrm5RKGvVEFQD9R3r/rbXT1x5qo99awsc0os3+/SFseRdHatQM3dLmm2O00uHrbCoW89N/8l+omKcvrfDtL5iN7Tpn/JzEBotKJXHXycWzcGT7BI7acmnXenWJE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
